server:
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    excluded-user-agents: MSIE 6.0,UCBrowser
    min-response-size: '1024'
  address: 0.0.0.0
  port: '8080'

spring:
  profiles:
    include: 'db'
  application:
    name: helper
  devtools:
    restart:
      addtional-exlclude: main/**
      enabled: 'true'
    livereload:
      enabled: 'true'
  thymeleaf:
    cache: 'false'
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
  datasource:
    password: ahuser01!
    driver-class-name: org.mariadb.jdbc.Driver
    username: albionhelper_user01
    url: jdbc:mariadb://localhost:3306/albiondb?characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  output:
    ansi:
      enabled: always
